on:
  push:
    branches: [dev, qa, main]
jobs: 
  #DEV

  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"
  cloudrun-dev:
    name: deploy cloudrun to dev environment
    if: ${{ github.ref == 'refs/heads/dev' || github.base_ref == 'dev' }}
    uses: ./.github/workflows/_deployment.yaml
    permissions: 
      id-token: write
      contents: read
    with: 
      environment: dev
      ref: ${{ github.sha }}
    secrets: inherit
  
  #QA
  qa:
    if: ${{ github.ref == 'refs/heads/qa' || github.base_ref == 'qa' }}
    uses: ./.github/workflows/_deployment.yaml
    permissions: 
      id-token: write
      contents: read
    with: 
      environment: qa
      ref: ${{ github.sha }}
      #serverless_conn_name: ${{ var.serverless_conn_name }}
    secrets: inherit
  
  #PROD
  prod: 
    if: ${{ github.ref == 'refs/heads/main' || github.base_ref == 'main' }}
    uses: ./.github/workflows/_deployment.yaml
    permissions: 
      id-token: write
      contents: read
    with:
      environment: prod
      ref: ${{ github.sha }}
      #serverless_conn_name: ${{ var.serverless_conn_name }}
    secrets: inherit