on:
  pull_request:
    branches: [dev, qa, main]
    types: [opened, reopened, synchronize]
jobs: 
  #DEV
  dev:
    if: ${{ github.ref == 'refs/heads/dev' || github.base_ref == 'dev' }}
    uses: ./.github/workflows/_deployment.yaml
    permissions: 
      id-token: write
      contents: read
    with: 
      environment: dev
      ref: ${{ github.sha }}
    secrets: inherit
  #QA
  qa:
    if: ${{ github.ref == 'refs/heads/qa' || github.base_ref == 'qa' }}
    uses: ./.github/workflows/_deployment.yaml
    permissions: 
      id-token: write
      contents: read
    with: 
      environment: qa
      ref: ${{ github.sha }}
    secrets: inherit
  
  #PROD
  prod: 
    if: ${{ github.ref == 'refs/heads/main' || github.base_ref == 'main' }}
    uses: ./.github/workflows/_deployment.yaml
    permissions: 
      id-token: write
      contents: read
    with:
      environment: prod
      ref: ${{ github.sha }}
    secrets: inherit